name: contribution-streak-maintainer

on:
  workflow_dispatch:
  schedule:
    # This cron schedule means the action runs every day at 22:00 UTC.
    - cron: "0 22 * * *"

permissions:
  contents: write

jobs:
  contribution-streak-maintainer:
    runs-on: ubuntu-latest
    steps:
      - name: Make a contribution
        run: npx contribution-streak-maintainer ${{github.repository}} --email=your-primary-github-email@gmail.com
        env:
          DEVFUL_GITHUB_TOKEN: ${{ secrets.CSM_GITHUB_TOKEN }}
